name: fitanalyser
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=3.5.0
  - argon2-cffi=20.1.0
  - astroid=2.4.2
  - async_generator=1.10
  - attrs=20.3.0
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - bleach=3.2.1
  - branca=0.4.1
  - brotlipy=0.7.0
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - cffi=1.14.4
  - chardet=3.0.4
  - colorama=0.4.4
  - cryptography=3.2.1
  - cycler=0.10.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - folium=0.12.1.post1
  - freetype=2.10.4
  - icu=67.1
  - idna=2.10
  - importlib-metadata=3.1.1
  - importlib_metadata=3.1.1
  - intel-openmp=2020.3
  - ipykernel=5.3.4
  - ipython=7.19.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - isort=5.6.4
  - jedi=0.17.2
  - jinja2=2.11.2
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.2.0
  - jupyter_core=4.7.0
  - jupyter_server=1.15.6
  - jupyterlab=3.3.2
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.10.3
  - kiwisolver=1.3.1
  - lazy-object-proxy=1.4.3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=10.0.1
  - liblapack=3.8.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.1.0
  - lz4-c=1.9.2
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=1.1.1
  - matplotlib=3.3.3
  - matplotlib-base=3.3.3
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2020.4
  - msys2-conda-epoch=20160418
  - nbclassic=0.3.7
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.0.8
  - nest-asyncio=1.4.3
  - notebook=6.1.5
  - notebook-shim=0.1.0
  - numpy=1.22.0
  - olefile=0.46
  - openssl=1.1.1l
  - packaging=20.7
  - pandas=1.3.5
  - pandoc=2.11.2
  - pandocfilters=1.4.2
  - parso=0.7.1
  - pathlib=1.0.1
  - pickleshare=0.7.5
  - pillow=8.0.1
  - pip=22.0.4
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.8
  - prompt_toolkit=3.0.8
  - pycparser=2.20
  - pygments=2.7.2
  - pylint=2.6.0
  - pyopenssl=20.0.0
  - pyparsing=2.4.7
  - pyprojroot=0.2.0
  - pyqt=5.12.3
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.8.8
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2020.4
  - pywin32=228
  - pywinpty=0.5.7
  - pyzmq=20.0.0
  - qt=5.12.9
  - qtconsole=5.0.1
  - qtpy=1.9.0
  - requests=2.25.0
  - send2trash=1.5.0
  - setuptools=59.8.0
  - six=1.15.0
  - sniffio=1.2.0
  - sqlite=3.34.0
  - terminado=0.9.1
  - testpath=0.4.4
  - tk=8.6.10
  - toml=0.10.1
  - tornado=6.1
  - tqdm=4.63.0
  - traitlets=5.0.5
  - urllib3=1.25.11
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.3.1
  - wheel=0.36.1
  - widgetsnbextension=3.5.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - wrapt=1.11.2
  - xz=5.2.5
  - zeromq=4.3.3
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - fitparse==1.2.0
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1

