name: fitanalyser
channels:
  - conda-forge
  - defaults
dependencies:
  - python =3.8         # python
  - pip >=20.3          # python package manager
  - setuptools >=49.1   # set up local package
  - jupyter >= 1.0      # notebooks
  - tqdm >=4.54         # progress bar
  - numpy >=1.19        # numeric arrays
  - pandas >=1.1        # data frames
  - matplotlib >=3.3    # basic plotting  
  - folium >=0.11       # map visualisations
  - pyprojroot >=0.2    # finding project directories
  - pylint >=2.6        # static code analysis tool
  - pip:
    - fitparse >=1.2    # parsing garmin fit files
